"""Professional PDF threat-report export (fpdf2, core fonts)."""

from fpdf import FPDF

ACCENT = (0, 150, 200)
DARK = (20, 25, 40)
GRAY = (110, 115, 130)


def _safe(text: str) -> str:
    """Core PDF fonts are latin-1 only — strip the rest (emojis etc.)."""
    return (text or "").encode("latin-1", errors="ignore").decode("latin-1")


class ThreatPDF(FPDF):
    def header(self):
        self.set_fill_color(*DARK)
        self.rect(0, 0, 210, 26, "F")
        self.set_xy(12, 7)
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(255, 255, 255)
        self.cell(0, 8, "THREAT INTELLIGENCE REPORT", ln=True)
        self.set_x(12)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*GRAY)
        self.cell(0, 6, "Generated by Threat Analyzer  |  NLP-based Cybersecurity Report Analyzer")

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*GRAY)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

    def section(self, title: str):
        self.ln(4)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(*ACCENT)
        self.cell(0, 8, _safe(title).upper(), ln=True)
        self.set_draw_color(*ACCENT)
        self.line(12, self.get_y(), 198, self.get_y())
        self.ln(2)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(40, 40, 40)
        self.multi_cell(0, 6, _safe(text))
        self.ln(1)

    def bullet(self, text: str, bold_prefix: str = ""):
        line = "- " + (f"**{_safe(bold_prefix)}** " if bold_prefix else "") + _safe(text)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(40, 40, 40)
        self.multi_cell(0, 6, line, markdown=True)
        self.ln(1)


def generate_pdf(result: dict) -> bytes:
    pdf = ThreatPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*DARK)
    pdf.cell(0, 10, _safe(result["filename"]), ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*GRAY)
    pdf.cell(0, 6, f"Threat Type: {result['threat_type']}    |    "
                   f"Severity: {result['severity']}    |    "
                   f"Words analyzed: {result['word_count']}", ln=True)

    pdf.section("Executive Summary")
    pdf.body_text(result["summary"])

    pdf.section("Vulnerabilities (with CVSS)")
    cves = result.get("cves_enriched") or [{"id": c} for c in result["iocs"]["cves"]]
    if cves:
        for c in cves:
            extra = ""
            if c.get("score") is not None:
                extra = f"  [CVSS {c['score']} ({c.get('severity') or 'n/a'})]"
            pdf.bullet(c["id"] + extra)
    else:
        pdf.body_text("None found.")

    pdf.section("Attack Techniques (MITRE ATT&CK)")
    if result["techniques"]:
        for t in result["techniques"]:
            pdf.bullet(f"{t['name']} ({t['tactic']})", bold_prefix=t["id"])
    else:
        pdf.body_text("None mapped.")

    pdf.section("Indicators of Compromise")
    any_ioc = False
    for label, vals in result["iocs"].items():
        if vals:
            any_ioc = True
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*DARK)
            pdf.cell(0, 7, label.upper(), ln=True)
            for v in vals:
                pdf.bullet(v)
    if not any_ioc:
        pdf.body_text("None found.")

    if result.get("timeline"):
        pdf.section("Attack Timeline")
        for ev in result["timeline"]:
            pdf.bullet(ev["event"], bold_prefix=ev["date"] + " -")

    pdf.section("Recommended Actions")
    for i, a in enumerate(result["recommended_actions"], 1):
        pdf.bullet(a, bold_prefix=f"{i}.")

    return bytes(pdf.output())
